repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.11.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-requests, types-PyYAML]
  #       args: [--ignore-missing-imports, --no-strict-optional]
  #       exclude: ^(modules/|data_processing/get_raw/|test_|tests/)
